meta_product_name: "Matria"
meta_title: "Matria - Red de apoyo y acompañamiento"
meta_description: "Red de apoyo del FNCVV, dedicada a brindar acompañamiento integral y herramientas comunitarias para mujeres que están viviendo situación de violencia vicaria."
meta_image: "logo.matria.png"
twitter_account: "@matria_app"
